# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_plugin('vagrant-hostmanager')

Vagrant.configure('2') do |config|
  config.vm.box = 'precise32'
  config.vm.box_url = 'http://files.vagrantup.com/precise32.box'

  config.hostmanager.auto_update = false

  config.vm.define :server1 do |server|
    server.vm.hostname = 'fry.example.org'
    server.vm.network :private_network, :ip => '10.0.5.2'
    server.hostmanager.aliases = %w(fry42.example.org fry-old.example.org)
  end

  config.vm.define :server2 do |server|
    server.vm.hostname = 'bender.example.org'
    server.vm.network :private_network, :ip => '10.0.5.3'
    server.hostmanager.aliases = %w(bender42.example.org bender-old.example.org)
  end
end
